from crewai import Task


def create_tasks(news_researcher, news_writer):
    """Create fresh CrewAI tasks for each article generation request."""

    research_task = Task(
        description=(
            "Prepare a structured research brief about {topic} using ONLY the "
            "research data provided below.\n\n"
            "RESEARCH DATA:\n"
            "{research}\n\n"
            "The research data above was retrieved from the application's "
            "news search tool. Do NOT perform another search and do NOT use "
            "outside knowledge to supplement it. "
            "First, identify the articles and sources that are actually "
            "relevant to {topic}. Ignore retrieved articles that are not "
            "relevant to the requested topic. "
            "Base every factual statement in the research brief strictly on "
            "information explicitly present in the provided research data. "
            "For every factual claim, identify the supporting source whenever "
            "the source information is available. Preserve the original source "
            "name and source link. "
            "Do not invent facts, statistics, events, dates, quotations, "
            "organizations, technologies, motivations, causes, or conclusions. "
            "Do not infer organizational intent or motives. "
            "When reporting a person's statement, clearly attribute the "
            "statement to that person and identify the source reporting it. "
            "Do not combine information from separate articles into a new "
            "conclusion unless the relationship is explicitly supported by "
            "the provided research data. "
            "Do not describe something as a conflict, trend, crisis, "
            "significant development, growing problem, breakthrough, "
            "industry shift, or similar characterization unless the provided "
            "sources explicitly support that characterization. "
            "If the sources only report an event, report the event without "
            "adding interpretation. "
            "If sources disagree or present different perspectives, preserve "
            "the distinction and attribute each perspective to its source "
            "rather than attempting to resolve the disagreement. "
            "If the provided research does not contain enough information to "
            "support a claim, explicitly state that the available sources "
            "do not provide sufficient information. Do not fill the gap using "
            "general knowledge. "
            "If an implication is useful, place it in a separate "
            "'Potential Implications' section and clearly label it as an "
            "inference. Do not present an inference as an established fact."
        ),
        expected_output=(
            "A structured research brief in Markdown containing:\n\n"
            "## Relevant Sources\n"
            "For each relevant article:\n"
            "- Article title\n"
            "- Source\n"
            "- Date, when available\n"
            "- URL\n"
            "- Brief summary of what the source explicitly reports\n\n"
            "## Reported Developments\n"
            "A factual summary of the developments explicitly supported "
            "by the retrieved sources.\n\n"
            "## Key Facts\n"
            "Important facts that can be directly traced to the retrieved "
            "sources. Include source attribution.\n\n"
            "## Organizations and Technologies Mentioned\n"
            "Organizations, products, models, technologies, or other entities "
            "explicitly mentioned by the sources.\n\n"
            "## Potential Implications\n"
            "Only include implications that can reasonably be derived from "
            "the provided research. Clearly label these as inference.\n\n"
            "## Sources\n"
            "List the original source links.\n\n"
            "Every factual item must be traceable to the provided research. "
            "Do not introduce information that is absent from the research."
        ),
        agent=news_researcher,
    )

    write_task = Task(
        description=(
            "Write a clear, accurate, and engaging technology article "
            "about {topic} using ONLY the research brief produced by "
            "the researcher.\n\n"
            "Write the article in the requested style: {article_style}. "
            "Target the requested length: {article_length}.\n\n"
            "Style requirements:\n"
            "- News Report: factual, concise, journalistic, and focused on "
            "reported developments.\n"
            "- Research Brief: structured, analytical, and organized around "
            "facts, sources, and findings.\n"
            "- Explainer: educational and easy to follow, explaining the "
            "reported developments clearly without adding unsupported information.\n\n"
            "Length requirements:\n"
            "- Short: approximately 400-600 words.\n"
            "- Medium: approximately 700-900 words.\n"
            "- Detailed: approximately 1000-1300 words.\n\n"
            "The research brief is the sole factual basis for the article. "
            "Do NOT perform additional research and do NOT introduce outside "
            "knowledge. "
            "Preserve the factual meaning of the research brief while "
            "rewriting it into a readable article. "
            "Do not introduce facts, statistics, events, dates, quotations, "
            "organizations, technologies, motivations, opinions, predictions, "
            "or causal explanations that are not explicitly supported by "
            "the research brief. "
            "When describing a person's statement, clearly attribute the "
            "statement to that person and the relevant source. "
            "When describing a claim, interpretation, or potentially disputed "
            "point, make the attribution clear rather than presenting it as "
            "an independently established fact. "
            "Do not present speculation or inference as established fact. "
            "Do not infer motives from corporate, organizational, political, "
            "or individual decisions. "
            "Do not exaggerate the importance of an event or describe it as "
            "a breakthrough, crisis, major shift, controversy, or similar "
            "characterization unless that characterization is supported by "
            "the research brief. "
            "If the research brief contains insufficient information about "
            "an aspect of the topic, do not fill the gap with general "
            "knowledge. Simply omit the unsupported detail. "
            "Preserve the distinction between reported facts and potential "
            "implications. Any implication included in the research brief "
            "must remain clearly identifiable as an inference in the article. "
            "Preserve the original source links supplied in the research "
            "brief. Do not create or modify URLs."
        ),
        expected_output=(
            "A polished Markdown technology news article containing:\n\n"
            "# Headline\n"
            "A clear and informative headline based only on the research.\n\n"
            "## Introduction\n"
            "A concise introduction explaining what the retrieved sources "
            "report about the topic.\n\n"
            "## Main Developments\n"
            "The key developments and supporting details, with appropriate "
            "source attribution.\n\n"
            "## Context\n"
            "Relevant context explicitly supported by the research brief.\n\n"
            "## Potential Implications\n"
            "Only if supported by the research brief. Clearly distinguish "
            "inference from established facts.\n\n"
            "## Sources\n"
            "A list of the source names and original URLs provided in the "
            "research brief.\n\n"
            "The article must remain completely grounded in the research "
            "brief and must not introduce unsupported information."
        ),
        agent=news_writer,
        context=[research_task],
    )

    return research_task, write_task
